---
- hosts: all
  remote_user: ec2-user
  tasks:
  - name: Test for signs of life
    ping:
  - name: Is nginx in the heezy?
    yum:
     name: nginx
     state: present
  - name: Is nginx smelling roses?
    service:
     name: nginx
     state: started
