---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo

  tasks:
    - name: Ping check.
      ping:

    - name: Nginx installation status?
      yum:
        name: nginx
        state: present

    - name: Is nginx running?
      service:
        name: nginx
        state: started