---
- hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  
  tasks:
    - name: Shutdown nginx.
      service:
        name: nginx
        state: stopped

    - name: Uninstall nginx
      yum:
        name: nginx
        state: absent
