---
- hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  tasks:
    - name: Test if everyone is alive and well.
      ping:
  
    - name: Install nginx
      yum:
      name: nginx
        state: present
  
    - name: Is nginx running?
      service:
        name: nginx
        state: started
