---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped

    - name: Uninstall
      yum:
        name: nginx
        state: absent